# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

mkdocs:
  configureation: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
